In [1]:
import numpy as np
import matplotlib.pyplot as plt
from safety_formation.formation import Agent,Topology

In [ ]:
A = np.array([
    [ 0, 1,  0,  0,  0, 1],
    [ 1,  0, 1,  0,  0,  0],
    [ 0, 1,  0, 1,  0,  0],
    [ 0,  0, 1,  0, 1,  0],
    [ 0,  0,  0, 1,  0, 1],
    [ 1,  0,  0,  0, 1,  0],
], dtype=float)

topology = Topology(num_agents=6, adjacency_matrix= A, leader_access= [1, 0 , 1, 0, 0, 0])

print(topology.laplacian_matrix)
print(topology.augmented_laplacian)
print(topology.get_neighbors(3))
print(topology)

[[ 2. -1.  0.  0.  0. -1.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [-1.  0.  0.  0. -1.  2.]]
[[ 3. -1.  0.  0.  0. -1.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  3. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [-1.  0.  0.  0. -1.  2.]]
[2 4]
Topology(n=6, Leader_Linked=True)
